name: SonarCloud Analysis

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Run Tests and SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      # 1. Baixar o código do repositório
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configurar a versão do Python que você usa
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Substitua pela sua versão

      # 3. Instalar as dependências do projeto e ferramentas de teste
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      # 4. Executar os testes e gerar os relatórios
      - name: Run tests with coverage
        run: |
          uv run pytest --cov=./src --cov-report=xml:coverage.xml --junitxml=tests/test-results.xml tests/ -v
          rm  -rf src/database/data/db_test.sql

      # 5. Escanear o código com o SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
